// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for oneM2MTester (martin@ubuntu) on Sun Apr  9 21:00:53 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "InfoPort.hh"

namespace OneM2M__Ports {

	InfoPort::InfoPort(const char *par_port_name) : InfoPort_BASE(par_port_name) {

	}

	InfoPort::~InfoPort() {

	}

	void InfoPort::set_parameter(const char * /*parameter_name*/, const char * /*parameter_value*/) {

	}

	/*void AdapterControlPort::Handle_Fd_Event(int fd, boolean is_readable, boolean is_writable, boolean is_error) {}*/

	void InfoPort::Handle_Fd_Event_Error(int /*fd*/) {

	}

	void InfoPort::Handle_Fd_Event_Writable(int /*fd*/) {

	}

	void InfoPort::Handle_Fd_Event_Readable(int /*fd*/) {

	}

	/*void AdapterControlPort::Handle_Timeout(double time_since_last_call) {}*/

	void InfoPort::user_map(const char * /*system_port*/) {

	}

	void InfoPort::user_unmap(const char * /*system_port*/) {

	}

	void InfoPort::user_start() {

	}

	void InfoPort::user_stop() {

	}

	void InfoPort::outgoing_send(const OneM2M__Types::RequestPrimitive&) {

	}

	void InfoPort::outgoing_send(const OneM2M__Types::ResponsePrimitive&) {

	}

	void InfoPort::outgoing_send(const OneM2M__Types::PrimitiveContent&) {

	}

	void InfoPort::outgoing_send(const OneM2M__Types::MyResource&) {

	}

	void InfoPort::outgoing_send(const INTEGER&) {

	}

	void InfoPort::outgoing_send(const UNIVERSAL_CHARSTRING&) {

	}

} /* end of namespace */

