.******************************************************************************
.* Copyright (C) 2017 ETSI  All Rights Reserved.
.*
.* Contributors:
.*   Adrien Kirjak 
.*
.******************************************************************************/
text.
:lang eng.
.*
:docname.Test Description
:docno.xz/152 91-CRL 113 200 Uen
:rev.PA1
:date.2016-04-04
.*
:prep.ETH/XZ EADRKIR
:subresp.EADRKIR
:appr.ETH/XZ (Elemer Lelik)
:checked.
.*
:title.ETSI TTCN3 Negative Conformance Test
:contents level=3.
.*---------------------------------------------------------------------*
:h1.PREREQUISITES AND PREPARATIONS
.*---------------------------------------------------------------------*	
.*---------------------------------------------------------------------*
:h2.Scope of the Test Object
.*---------------------------------------------------------------------*
:xmp tab=1 nokeep.
This TD contains syntactic tests with empty modules from ETSI TTCN3 Conformance Test's 08_modules folders. 

:exmp.

.*---------------------------------------------------------------------*
:h2.Test Tools
.*---------------------------------------------------------------------*
:p.:us.Software Tools:eus.
:xmp tab=2 nokeep.

	SAtester.pl

:exmp.
:np.

.*---------------------------------------------------------------------*
:h1.REQUIREMENT-BASED TESTS
.*---------------------------------------------------------------------*
.*---------------------------------------------------------------------*
:h2. 0801_definition_of_a_module folder
.*---------------------------------------------------------------------*
*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_001 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_001 Ensure that a "plain" module definition is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_001 Syn_0801_DefinitionOfAModule_001.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a "plain" module definition is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_001 {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_002 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_002 Ensure that a module definition with language specification is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_002 Syn_0801_DefinitionOfAModule_002.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with language specification is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_002 language "TTCN-3:2005" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_004 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_004 Ensure that a module definition with package and without language is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_004 Syn_0801_DefinitionOfAModule_004.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with package and without language is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_004 language "TTCN-3:2010 Advanced Parameterization" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_005 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_005 Ensure that a module definition with ed4.3.1 language and package is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_005 Syn_0801_DefinitionOfAModule_005.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with ed4.3.1 language and package is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_005 language "TTCN-3:2011" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_006 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_006 Ensure that a module definition with ed4.4.1 language and package is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_006 Syn_0801_DefinitionOfAModule_006.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with ed4.4.1 language and package is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_006 language "TTCN-3:2012" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_007 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_007 Ensure that a module definition with ed4.5.1 language and package is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_007 Syn_0801_DefinitionOfAModule_007.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with ed4.5.1 language and package is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_007 language "TTCN-3:2013" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_008 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_008 Ensure that a module definition with ed4.6.1 language and package is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_008 Syn_0801_DefinitionOfAModule_008.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with ed4.6.1 language and package is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_008 language "TTCN-3:2014" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0801_DefinitionOfAModule_009 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0801_009 Ensure that a module definition with ed4.7.1 language and package is accepted. >

<COMPILE>

<MODULE TTCN Syn_0801_DefinitionOfAModule_009 Syn_0801_DefinitionOfAModule_009.ttcn >
/*****************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.1, Ensure that a module definition with ed4.7.1 language and package is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0801_DefinitionOfAModule_009 language "TTCN-3:2015" {

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

*---------------------------------------------------------------------*
:h3. Syn_0803_ModuleControlPart_003 negative test
.*---------------------------------------------------------------------*
:xmp tab=0.

<TC - 0803_003 Ensure that an empty control part is accepted. >

<COMPILE>

<MODULE TTCN Syn_0803_ModuleControlPart_003 Syn_0803_ModuleControlPart_003.ttcn >
/******************************************************************************
 ** @version  0.0.1
 ** @purpose  1:8.3, Ensure that an empty control part is accepted.
 ** @verdict  pass accept, noexecution
 *****************************************************************/

module Syn_0803_ModuleControlPart_003 {

	control {
	
	}

}
<END_MODULE>

<RESULT IF_PASS NEGATIVE>
error
<END_RESULT>

<END_TC>
:exmp

.*---------------------------------------------------------------------*
:h1.References
.*---------------------------------------------------------------------*
:list.
:li D='[1]'.1/1/174 02-CRL 113 200/5 Uen
:nl.Statement of Compliance for TITAN project
:li D='[2]'.ETSI ES 201 873-1, v4.7.1 Mockup v1 (2015-06):
:nl.Testing and Test Control Notation version 3.,
:nl.Part 1: TTCN-3 Core Language
:elist.
