.TH ttcn3_profmerge 1 "August 2015" "Ericsson Telecom AB" "TTCN-3 Tools" 
.SH NAME
ttcn3_profmerge \- TTCN-3 profiler and code coverage merge tool
.SH SYNOPSIS
.B ttcn3_profmerge
.RB "[ " \-pc
.RB "] [ " \-o
.I "file"
.RB "] [ " \-s
.IR "file" " ]"
.RB "[ " \-f
.IR "filter" " ]"
.IR db_file1 " ["
.IR db_file2 " ... ]"
.br
or
.br
.B ttcn3_profmerge
.B \-v
.SH DESCRIPTION
This manual page is a quick reference for the TTCN-3 profmerge utility of
the TTCN-3 Test Executor. The 
.B ttcn3_profmerge
utility, which can be found in 
.I $TTCN3_DIR/bin,
merges all input files (profiler databases) given in the command argument into a
single output file. It can also generate profiler statistics from the merged
database.
.br
Since there are two possible outputs, neither of them are written to the standard output.
.br
It is useful for test suites that are run on multiple Host Controllers (in parallel mode).
.SH OPTIONS
Available command line switches are:
.TP 10
.B \-p
Discards profiler data from the merged database. All execution times will be set to zero in
the output database file, and statistics related to execution times will not be generated (both
profiler and code coverage data cannot be discarded, since there would be no data left).
.TP
.B \-c
Discards code coverage data from the merged database. All execution counts will be set to zero in
the output database file, and statistics related to execution counts will not be generated (both
profiler and code coverage data cannot be discarded, since there would be no data left).
.TP
.BI \-o " file"
Prints the output (merged) database to the specified
.IR file \.
At least one output file (this or the statistics file) must be set.
.TP
.BI \-s " file"
Prints statistics for the merged database into the specified
.IR file \.
At least one output file (this or the output database file) must be set.
.TP
.BI \-f " filter"
Specifies which statistics entries are generated. The
.I filter
is a hexadecimal number, the last 25 bits each correspond to the 25 entries
in the statistics file (the least significant bit corresponds to the first entry,
and so on). The filter is ignored if the statistics file is not set.
.TP
.B \-v
Prints
.I version
and license key information and exits.
.SH ENVIRONMENT VARIABLES
.TP
.SM
TTCN3_DIR
The installation directory where the uncompressed binary package of the
TTCN-3 Test Executor can be found.
.TP
.SM
TTCN3_LICENSE_FILE
Points to the
.I file
.RB ( NB:
.I not
the directory) that contains the personalized license key for the
current user or host.
.SH BUGS
None known at this time
.LP
.SH SEE ALSO
The
.B Programmer's Technical Reference for the TTCN-3
.B Test Executor.
.SH AUTHOR
This manpage is written by Botond Baranyi, Ericsson Telecom AB
.br
Copyright (c) 2000-2017 Ericsson Telecom AB
.br
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
.br
http://www.eclipse.org/legal/epl-v10.html
