#!/bin/sh
#
#echo "*****************************************************"
#echo "Ez egy tok primitiv automatizalt teszter V0.0" 
#echo "ami osszehasonlit ket ASN.1-bol forditott cc filenek kiragadott reszeit
#echo "*****************************************************"
#echo""

function_check()
{
    TestID=$1

    sed -n "/\/\* Global variable definitions \*\//,/\/\* Member functions of C++ classes \*\//{
	s/${TestID}A/${TestID}X/g
	p
    }" ${TestID}A.cc >DummyA

    sed -n "/\/\* Global variable definitions \*\//,/\/\* Member functions of C++ classes \*\//{
	s/${TestID}B/${TestID}X/g
	p
    }" ${TestID}B.cc >DummyB

    if cmp -s ./DummyA ./DummyB
    then
	Verdict="pass"
	rm ${TestID}[AB].{hh,cc}
    else
	Verdict="fail"
    fi

    echo "ASN1:$TestID = Verdict $Verdict"
    rm ./Dummy[AB]
}

function_check Test38
