#!/bin/sh
# the next line restarts using expect \
exec expect "$0" "$@"

#####################################################
##                                                 ##
##  EXPECT script to automate TTCN-3 testing       ##
##                                                 ##
##                                                 ##
#####################################################

