// This Test Port skeleton header file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for oneM2MTester (martin@ubuntu) on Sun Apr  9 21:00:53 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// You may modify this file. Add your attributes and prototypes of your
// member functions here.

#ifndef AdapterControlPort_HH
#define AdapterControlPort_HH

#include "OneM2M_Ports.hh"

namespace OneM2M__Ports {

class AdapterControlPort : public AdapterControlPort_BASE {
	public:
		AdapterControlPort(const char *par_port_name = NULL);
		~AdapterControlPort();

		void set_parameter(const char *parameter_name,
			const char *parameter_value);

	private:
		/* void Handle_Fd_Event(int fd, boolean is_readable,
			boolean is_writable, boolean is_error); */
		void Handle_Fd_Event_Error(int fd);
		void Handle_Fd_Event_Writable(int fd);
		void Handle_Fd_Event_Readable(int fd);
		/* void Handle_Timeout(double time_since_last_call); */
	protected:
		void user_map(const char *system_port);
		void user_unmap(const char *system_port);

		void user_start();
		void user_stop();

		void outgoing_send(const OneM2M__Types::AcRequestPrimitive& send_par);
	};
} /* end of namespace */

#endif
