// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/6 R1A
// for oneM2MTester (martin@ubuntu) on Sun Apr  9 21:00:53 2017

// Copyright (c) 2000-2017 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "AdapterControlPort.hh"

namespace OneM2M__Ports {

	AdapterControlPort::AdapterControlPort(const char *par_port_name) : AdapterControlPort_BASE(par_port_name) {

	}

	AdapterControlPort::~AdapterControlPort() {

	}

	void AdapterControlPort::set_parameter(const char * /*parameter_name*/, const char * /*parameter_value*/) {

	}

	/*void AdapterControlPort::Handle_Fd_Event(int fd, boolean is_readable, boolean is_writable, boolean is_error) {}*/

	void AdapterControlPort::Handle_Fd_Event_Error(int /*fd*/) {

	}

	void AdapterControlPort::Handle_Fd_Event_Writable(int /*fd*/) {

	}

	void AdapterControlPort::Handle_Fd_Event_Readable(int /*fd*/) {

	}

	/*void AdapterControlPort::Handle_Timeout(double time_since_last_call) {}*/

	void AdapterControlPort::user_map(const char * /*system_port*/) {

	}

	void AdapterControlPort::user_unmap(const char * /*system_port*/) {

	}

	void AdapterControlPort::user_start() {

	}

	void AdapterControlPort::user_stop() {

	}

	void AdapterControlPort::outgoing_send(const OneM2M__Types::AcRequestPrimitive& /*send_par*/) {

	}
} /* end of namespace */

