#!/bin/sh
#
#echo "*****************************************************"
#echo "Ez egy negyedik tok primitiv automatizalt teszter V0.0"
#echo "ami megnezi greppel az extension utani integer hozzarendelest

#echo "*****************************************************"

if  
  $GREP -q "c = 2" ./Test25.hh
      then
        if 
           $GREP -q "d = 3" ./Test25.hh
                then
                    if
		         $GREP -q "e = 3" ./Test25.hh
		              then 
			          if
				   $GREP -q "f = 0" ./Test25.hh
				      then
				         if 
				           $GREP -q "g = 1" ./Test25.hh
				                then
				                  if 
						     $GREP -q "h = 2" ./Test25.hh
						      then Verdict="pass"
						  
						      else Verdict="fail 6"
				                  fi
				            else Verdict="fail 5"  
				         fi
		                   
		                   else Verdict="fail 4"
		                  fi
		         else  Verdict="fail 3"
		    fi
		else  Verdict="fail 2"
        fi
     else Verdict="fail 1"
fi

echo "ASN1:TEST25 = Verdict: $Verdict"
