TTCN3_DIR   :={_home_directory_of_titan_core_}/Install
OPENSSL_DIR :=/usr
JDKDIR      :={_directory_of_jdk} e.g. /usr/lib/jvm/java-7-openjdk-amd64
XMLDIR      :=/usr
JNI         :=no  #disable JNI
GEN_PDF     :=no
#CXX         :=clang++-3.8
#CC          :=clang-3.8
