/******************************************************************************
 * Copyright (c) 2000-2017 Ericsson Telecom AB
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Balasko, Jeno
 *   Delic, Adam
 *   Lovassy, Arpad
 *   Szabados, Kristof
 *
 ******************************************************************************/
// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version 1.6.pl3
// for Kristof Szabados (ekrisza@balisea) on Wed Nov  9 10:02:40 2005


// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "separate_PT.hh"

namespace separate__ttcn {

separate__PT::separate__PT(const char *par_port_name)
	: separate__PT_BASE(par_port_name)
{

}

separate__PT::~separate__PT()
{

}

void separate__PT::set_parameter(const char *parameter_name,
	const char *parameter_value)
{

}

void separate__PT::Event_Handler(const fd_set *read_fds,
	const fd_set *write_fds, const fd_set *error_fds,
	double time_since_last_call)
{

}

void separate__PT::user_map(const char *system_port)
{

}

void separate__PT::user_unmap(const char *system_port)
{

}

void separate__PT::user_start()
{

}

void separate__PT::user_stop()
{

}

void separate__PT::outgoing_send(const CHARSTRING& send_par)
{

}

}
